kind: pipeline
name: default

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:6.0
    commands:
      - cd mvgd-net  # Entriamo nella cartella del progetto
      - dotnet publish -c Release -r linux-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:AssemblyName=${DRONE_REPO_NAME}_${DRONE_TAG}_linux-x64 -o ./publish/
      - dotnet publish -c Release -r linux-arm64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:AssemblyName=${DRONE_REPO_NAME}_${DRONE_TAG}_linux-arm64 -o ./publish/
      - dotnet publish -c Release -r osx-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:AssemblyName=${DRONE_REPO_NAME}_${DRONE_TAG}_osx-x64 -o ./publish/
      - dotnet publish -c Release -r osx-arm64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:AssemblyName=${DRONE_REPO_NAME}_${DRONE_TAG}_osx-arm64 -o ./publish/
      - dotnet publish -c Release -r win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:AssemblyName=${DRONE_REPO_NAME}_${DRONE_TAG}_win-x64 -o ./publish/
      - rm -rf ./publish/*.pdb

  - name: github release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_TOKEN
      files:
        - ./mvgd-net/publish/${DRONE_REPO_NAME}_*
      checksum:
        - sha256
    when:
      event:
        - tag

trigger:
  event:
    - tag