name: Build and release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build and Publish
        working-directory: ./mvgd-net
        run: |
          dotnet publish -c Release -r linux-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:AssemblyName=${{ github.repository }}_${{ github.ref }}_linux-x64 -o ./publish/
          dotnet publish -c Release -r linux-arm64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:AssemblyName=${{ github.repository }}_${{ github.ref }}_linux-arm64 -o ./publish/
          dotnet publish -c Release -r osx-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:AssemblyName=${{ github.repository }}_${{ github.ref }}_osx-x64 -o ./publish/
          dotnet publish -c Release -r osx-arm64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:AssemblyName=${{ github.repository }}_${{ github.ref }}_osx-arm64 -o ./publish/
          dotnet publish -c Release -r win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:AssemblyName=${{ github.repository }}_${{ github.ref }}_win-x64 -o ./publish/
          rm -rf ./publish/*.pdb

      - name: GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ./mvgd-net/publish/${{ github.repository }}_*
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          tag: ${{ github.ref }}